"""sales initial

Revision ID: 0001_sales_initial
Revises: 
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '0001_sales_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_inbox_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('crm_ref', sa.String(length=80), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_inbox_log_at'), 'sales_inbox_log', ['at'], unique=False)
    op.create_table('sales_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_no', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('item', sa.String(length=500), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('lead_type', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('follow_up_on', sa.Date(), nullable=True),
    sa.Column('heat', sa.String(length=10), nullable=False),
    sa.Column('heat_why', sa.Text(), nullable=True),
    sa.Column('heat_by', sa.String(length=500), nullable=True),
    sa.Column('rating_answers', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('priority_why', sa.Text(), nullable=True),
    sa.Column('priority_by', sa.String(length=500), nullable=True),
    sa.Column('value_lakh', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('value_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_basis', sa.String(length=80), nullable=True),
    sa.Column('closes_on', sa.Date(), nullable=True),
    sa.Column('is_prospect', sa.Boolean(), nullable=False),
    sa.Column('first_call_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asked_again_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crm_kind', sa.String(length=20), nullable=True),
    sa.Column('crm_ref', sa.String(length=80), nullable=True),
    sa.Column('crm_id', sa.Integer(), nullable=True),
    sa.Column('crm_close_pending', sa.String(length=30), nullable=True),
    sa.Column('disposal_reason', sa.String(length=30), nullable=True),
    sa.Column('disposal_note', sa.Text(), nullable=True),
    sa.Column('disposal_by', sa.Integer(), nullable=True),
    sa.Column('disposal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_no', sa.String(length=100), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm_kind', 'crm_ref', name='uq_sales_lead_crm'),
    sa.UniqueConstraint('lead_no')
    )
    op.create_index(op.f('ix_sales_lead_crm_ref'), 'sales_lead', ['crm_ref'], unique=False)
    op.create_index(op.f('ix_sales_lead_lead_type'), 'sales_lead', ['lead_type'], unique=False)
    op.create_index(op.f('ix_sales_lead_owner_user_id'), 'sales_lead', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_sales_lead_phone'), 'sales_lead', ['phone'], unique=False)
    op.create_index(op.f('ix_sales_lead_priority'), 'sales_lead', ['priority'], unique=False)
    op.create_index(op.f('ix_sales_lead_state'), 'sales_lead', ['state'], unique=False)
    op.create_index(op.f('ix_sales_lead_status'), 'sales_lead', ['status'], unique=False)
    op.create_table('sales_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_user_id', sa.Integer(), nullable=False),
    sa.Column('name_cache', sa.String(length=255), nullable=False),
    sa.Column('role_cache', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('extra_pincodes', sa.Text(), nullable=True),
    sa.Column('areas', sa.Text(), nullable=True),
    sa.Column('types_handled', sa.Text(), nullable=True),
    sa.Column('target_lakh', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_profile_crm_user_id'), 'sales_profile', ['crm_user_id'], unique=True)
    op.create_table('sales_role_tick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=20), nullable=False),
    sa.Column('tick_key', sa.String(length=60), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_key', 'tick_key', name='uq_sales_role_tick')
    )
    op.create_table('sales_setting',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sales_tick_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=20), nullable=True),
    sa.Column('crm_user_id', sa.Integer(), nullable=True),
    sa.Column('tick_key', sa.String(length=60), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=True),
    sa.Column('by_user_id', sa.Integer(), nullable=False),
    sa.Column('by_name', sa.String(length=255), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_tick_history_crm_user_id'), 'sales_tick_history', ['crm_user_id'], unique=False)
    op.create_table('sales_user_tick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_user_id', sa.Integer(), nullable=False),
    sa.Column('tick_key', sa.String(length=60), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm_user_id', 'tick_key', name='uq_sales_user_tick')
    )
    op.create_index(op.f('ix_sales_user_tick_crm_user_id'), 'sales_user_tick', ['crm_user_id'], unique=False)
    op.create_table('sales_lead_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('by_user_id', sa.Integer(), nullable=True),
    sa.Column('by_name', sa.String(length=255), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['sales_lead.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_lead_activity_lead_id'), 'sales_lead_activity', ['lead_id'], unique=False)
    op.create_table('sales_quotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_no', sa.String(length=40), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=60), nullable=True),
    sa.Column('valid_days', sa.Integer(), nullable=False),
    sa.Column('lead_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('delivery_terms', sa.Text(), nullable=True),
    sa.Column('warranty_terms', sa.Text(), nullable=True),
    sa.Column('reference_line', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('gross', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('taxable', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('high_discount', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_by_name', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['sales_lead.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_no')
    )
    op.create_index(op.f('ix_sales_quotation_lead_id'), 'sales_quotation', ['lead_id'], unique=False)
    op.create_index(op.f('ix_sales_quotation_status'), 'sales_quotation', ['status'], unique=False)
    op.create_table('sales_quotation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('by_user_id', sa.Integer(), nullable=True),
    sa.Column('by_name', sa.String(length=255), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['sales_quotation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_quotation_history_quotation_id'), 'sales_quotation_history', ['quotation_id'], unique=False)
    op.create_table('sales_quotation_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('hsn', sa.String(length=20), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('gst_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['sales_quotation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_quotation_line_quotation_id'), 'sales_quotation_line', ['quotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_quotation_line_quotation_id'), table_name='sales_quotation_line')
    op.drop_table('sales_quotation_line')
    op.drop_index(op.f('ix_sales_quotation_history_quotation_id'), table_name='sales_quotation_history')
    op.drop_table('sales_quotation_history')
    op.drop_index(op.f('ix_sales_quotation_status'), table_name='sales_quotation')
    op.drop_index(op.f('ix_sales_quotation_lead_id'), table_name='sales_quotation')
    op.drop_table('sales_quotation')
    op.drop_index(op.f('ix_sales_lead_activity_lead_id'), table_name='sales_lead_activity')
    op.drop_table('sales_lead_activity')
    op.drop_index(op.f('ix_sales_user_tick_crm_user_id'), table_name='sales_user_tick')
    op.drop_table('sales_user_tick')
    op.drop_index(op.f('ix_sales_tick_history_crm_user_id'), table_name='sales_tick_history')
    op.drop_table('sales_tick_history')
    op.drop_table('sales_setting')
    op.drop_table('sales_role_tick')
    op.drop_index(op.f('ix_sales_profile_crm_user_id'), table_name='sales_profile')
    op.drop_table('sales_profile')
    op.drop_index(op.f('ix_sales_lead_status'), table_name='sales_lead')
    op.drop_index(op.f('ix_sales_lead_state'), table_name='sales_lead')
    op.drop_index(op.f('ix_sales_lead_priority'), table_name='sales_lead')
    op.drop_index(op.f('ix_sales_lead_phone'), table_name='sales_lead')
    op.drop_index(op.f('ix_sales_lead_owner_user_id'), table_name='sales_lead')
    op.drop_index(op.f('ix_sales_lead_lead_type'), table_name='sales_lead')
    op.drop_index(op.f('ix_sales_lead_crm_ref'), table_name='sales_lead')
    op.drop_table('sales_lead')
    op.drop_index(op.f('ix_sales_inbox_log_at'), table_name='sales_inbox_log')
    op.drop_table('sales_inbox_log')
    # ### end Alembic commands ###
